In [1]:
import sys
import pandas as pd
import numpy as np
import navis
import pymaid
import random
import re
import ast
import json


import skeletor as sk
import cloudvolume as cv
import fafbseg
import caveclient
import k3d

D:\flywire_backup\cave\cave\lib\site-packages\blessed\terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-color'): Could not find terminal xterm-color
  warnings.warn(msg)

### auth and import

In [2]:
#megalopta project id: 8
#megalopta test project id: 25
#megalopta flywire project id: 28

path = 'D:/flywire_backup/cave/cat_client.json' # replace with your path

with open(path, 'r') as f:
    conn_file = json.load(f)
api_token = conn_file['api_token']
http_user = conn_file['http_user']
http_password = conn_file['http_password']
server = conn_file['server']

cat_client = pymaid.CatmaidInstance(server = server, 
                                api_token = api_token,
                                caching = True,
                                project_id = 8,
                                http_user = http_user,
                                http_password = http_password 
                                )

megalopta_flywire = pymaid.CatmaidInstance(server = server, 
                                api_token = api_token,
                                caching = True,
                                project_id = 28,
                                http_user = http_user,
                                http_password = http_password 
                                )


client = caveclient.CAVEclient(server_address='https://global.connectomics.braininbrain.org')

client_pb = caveclient.CAVEclient(datastack_name='megalopta_pb1_datastack')
auth_pb = client_pb.auth
cg_pb = client_pb.chunkedgraph
print('client set to PB data')

client_eb = caveclient.CAVEclient(datastack_name='megalopta_fb_eb_datastack', auth_token='34cfd1f903be508ac3068836dd10edc6')
auth_eb = client_eb.auth
cg_eb = client_eb.chunkedgraph
print('client set to EB data')


################################ other useful functions
# client.info.get_datastacks()
#print(f"My current token is: {auth.token}")

INFO  : Global CATMAID instance set. Caching is ON. (pymaid)
INFO  : Global CATMAID instance set. Caching is ON. (pymaid)

client set to PB data
client set to EB data

In [3]:
client_no = caveclient.CAVEclient(datastack_name='megalopta_no_r_datastack', auth_token='34cfd1f903be508ac3068836dd10edc6')
auth_no = client_no.auth
cg_no = client_no.chunkedgraph
print('client set to noduli data')

client set to noduli data

In [3]:
# Before we connect to the database we have to “monkey patch” cloudvolume such that it returns navis neurons:
# This needs to be run only once at the beginning of each session
# graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_PB1_v2a
# graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_FB_EB_v3
navis.patch_cloudvolume()
vol_eb = cv.CloudVolume('graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_FB_EB_v3', use_https=True, progress=False)
vol_pb = cv.CloudVolume('graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_PB1_v2a', use_https=True, progress=False)
vol_no = cv.CloudVolume('graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_NO_R_v4', use_https=True, progress=False)

INFO  : cloud-volume successfully patched! (navis)

In [4]:
# catmaid will create new ids for connectors, so this is just to make the uploader happy
# spatially overlapping connectors will be merged during upload, so no need to worry about uniqueness or duplicates

def id_generator(size: int = 7) -> str:
    """Creates a random string of digits of the specified length."""
    
    first_digit = random.choice('123456789')  # Ensures the first digit is not '0'
    remaining_digits = ''.join(random.choice('0123456789') for _ in range(size - 1))
    
    return first_digit + remaining_digits

print(id_generator())

resolution_xyz = np.unique([list(r.values()) for r in megalopta_flywire.image_stacks.resolution], axis=0).min(0).astype(int)

4198018

In [8]:
# associate pre/post L1 ids and updated roots with google sheet neurons (make sure to update root ids for those)

flywire_progress = pd.read_csv('./Eciton_FB neuron_CAVE progress - eciton_FB_PFN.csv', dtype=str)
n_table = flywire_progress #[flywire_progress['Catmaid name'].str.contains(neurons, na=False, regex=True)]

#select only relevant columns and rename for ease of use
nametable = n_table[['Catmaid name', 'Root ID', 'CATMAID skid']].rename(columns={'Catmaid name':'neuron_name', 'Root ID':'root_ids', 'CATMAID skid':'skid'})


nametable = nametable.dropna(subset='skid')

# nametable['skid'] = nametable['skid'].astype(int)
nametable['skid'] = nametable['skid'].fillna(0).astype(float).astype(int)

# probably a better way to do this...
# convert each cell in 'root_ids' from a comma-separated string to a list of integers, ignoring empty strings
# UNCOMMENT BELOW FOR MULTI ROOT
# nametable['root_ids'] = nametable['root_ids'].apply(lambda x: [int(seg) for seg in x.split(',') if seg.strip()])

nametable['root_ids'] = nametable['root_ids'].astype(str)

# Convert string representations of lists to actual lists
nametable['root_ids'] = nametable['root_ids'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x)

# Remove brackets by joining list elements into a string
nametable['root_ids'] = nametable['root_ids'].apply(lambda x: ', '.join(map(str, x)) if isinstance(x, list) else str(x))

nametable

                                  neuron_name            root_ids    skid
13                  PFN_LY_L4_AT_MS_VN2_PFN2E  504403158739739636   61663
23                     PFN_LY_L4_MS_VN3_PFN2E  504403158705447288  123278
24                     PFN_LY_L4_MS_VN4_PFN2E  504403158710540307  123288
25                     PFN_LY_L4_MS_VN5_PFN3E  504403158928391356  123298
26         PFN_LY_L4_MS_VN6__PFN4E_PFNc-maybe  504403158747624712  123325
27               PFN_LY_L4-maybe_MS_VN7_PFN5E  504403158700493608  123365
28                     PFN_LY_L4_MS_VN8_PFN5E  504403158803500127  123506
29                     PFN_LY_L4_MS_VN9_PFN4E  504403158688922673  123856
30       PFN_LY_L4-likely_MS_PFN5E_PFNc-maybe  504403158603543395  123863
31  PFN_LY_L4-likely_MS_VN10_PFN4E_PFNc-maybe  504403158695419734  123872
32                    PFN_LY_L4_MS_VN11_PFN4E  504403158737463008  123880
33                 PFN_LY_L4_MS_SH_VN13_PFN5E  504403158715955916  123886
34                  PFN_LY_L4-likely_MS_PFN5E  504403158761851136  123891
35             PFN_LY_L4-likely_MS_VN15_PFN4E  504403158791306619  123897
36             PFN_LY_L4-likely_MS_VN16_PFN4E  504403158831800648  123903
37                         PFN_LY_L4_MS_PFN5E  504403158699243479  123908
38                       PFNc_LY_L4-likely_MS  504403158657183148  123918
39                         PFNorPFNc_LY_L4_MS  504403158648259159  123925
43             PFN_LY_L4-likely_MS_VN18_PFN5E  504403158837397235  138882
46                    PFN_LY_L4_SH_VN12_PFN5E  504403158825550776  168429
47                    PFN_LY_L4_SH_VN19_PFN5E  504403158715958220  168434
48                    PFN_LY_L4_SH_VN20_PFN3E  504403158668220235  168439
49                    PFN_LY_L4_SH_VN21_PFN4E  504403158707673594  168444
50                    PFN_LY_L4_SH_VN22_PFN3E  504403158775326215  168449
51                    PFN_LY_L4_SH_VN23_PFN5E  504403158724681864  168454
52                    PFN_LY_L4_SH_VN24_PFN4E  504403158692562933  168464
53                    PFN_LY_L4_SH_VN25_PFN4E  504403158694176385  168469
54                    PFN_LY_L4_SH_VN26_PFN4E  504403158763516325  170237
55                           PFN_LY_L4_508397  504403158803758958  508397
56                    PFN_LY_L4_SH_VN27_PFN1E  504403158692214555  170242
57                    PFN_LY_L4_SH_VN28_PFN1E  504403158692180251  170247
58                    PFN_LY_L4_SH_VN29_PFN1E  504403158767404438  170252
59                    PFN_LY_L4_SH_VN30_PFN1E  504403158756464152  170257
60                    PFN_LY_L4_SH_VN31_PFN1E  504403158729655469  170279
61                    PFN_LY_L4_SH_VN32_PFN1E  504403158753444855  170284
62                    PFN_LY_L4_SH_VN33_PFN1E  504403158755930447  170289
63                    PFN_LY_L4_SH_VN34_PFN1E  504403158641032629  170294
64                    PFN_LY_L4_SH_VN35_PFN1E  504403158763835013  170299
65                    PFN_LY_L4_SH_VN36_PFN1E  504403158718007443  170304
66                PFN_LY_L4_cave-only-FB-data  504403158690793705  515109

In [10]:
# LNOs_a: 504403158459506101,
# LNOs_b: 504403158467123201, 
# LNOs_c: 504403158551966913
lno_list = [504403158459506101, 504403158467123201, 504403158551966913]
m = vol_no.mesh.get(lno_list, remove_duplicate_vertices=True, as_navis=True)

In [ ]:
'TN/LNO6_LNOs_a'
'TN/LNO4_LNOs_b'
'TN/LNO9_LNOs_c'

In [8]:
nametable = nametable.iloc[14:]

In [10]:
# separate nametable into two df: one with only single segids and another with lists of segids

# USER INPUT: set cloudvolume server
vol = vol_eb

#################################

oneRoot = nametable[~nametable['root_ids'].str.contains(',')] # check that string doesn't contain comma
multiRoot = nametable[nametable['root_ids'].str.contains(',')] # some roots are not merged due to NoneType error

oneRoot_list = oneRoot['root_ids'].tolist()
multiRoot_list = multiRoot['root_ids'].tolist()

# download neurons that have single root id
oneRoot_m = []

for idx, neuron in enumerate(oneRoot_list, start = 1):
    m = vol.mesh.get(neuron, remove_duplicate_vertices=True, as_navis=True)
    oneRoot_m.append(m)
    sys.stdout.write(f'\r{idx}/{len(oneRoot_list)} neuron mesh with single root downloaded.') # update console with progress
    sys.stdout.flush()

# download and fuse neurons that have multiple unmerged root ids

multiRoot_id_list = []
multiRoot_m = [] # mesh list

for idx, neuron in enumerate(multiRoot_list, start=1):
    n = list(neuron.strip().split(','))
    firstRoot = n[0]# multiRoot_list[0].split(',')[0].strip()
    multiRoot_id_list.append(firstRoot)
    m = vol.mesh.get(n, remove_duplicate_vertices=True, fuse=True, allow_missing=True, as_navis=True)
    multiRoot_m.append(m)
   
    sys.stdout.write(f'\r{idx}/{len(multiRoot_list)} neuron mesh with multi root ids downloaded and fused.') # update console with progress
    sys.stdout.flush()

oneRoot_m = navis.NeuronList(oneRoot_m)
multiRoot_m = navis.NeuronList(multiRoot_m)
multiRoot_m.set_neuron_attributes(multiRoot_id_list, name='id')

# merge oneRoot_m and multiRoot_m meshNeuronLists

# Check if both exist in the global namespace
if 'oneRoot_m' in globals() and 'multiRoot_m' in globals():
    m = oneRoot_m + multiRoot_m
    print(f'Combined list contains {len(m)} mesh neurons.')
elif 'oneRoot_m' in globals():
    m = oneRoot_m
    print(f'Combined list contains {len(m)} mesh neurons.')
elif 'multiRoot_m' in globals():
    m = multiRoot_m
    print(f'Combined list contains {len(m)} mesh neurons.')
else:
    print('uh-oh - major epic yikes sauce!')

4/4 neuron mesh with single root downloaded.Combined list contains 4 mesh neurons.

### fig 1 representative neurons

In [7]:
# epg_l3
m_eb = vol_eb.mesh.get(576460753102309773, remove_duplicate_vertices=True, as_navis=True)
m_pb = vol_pb.mesh.get([576460752504703640,576460752494001689], fuse=True, remove_duplicate_vertices=True, as_navis=True)
m = m_eb + m_pb

# peg_L2
m_eb = vol_eb.mesh.get(576460752959971604, remove_duplicate_vertices=True, as_navis=True)
m_pb = vol_pb.mesh.get([576460752482567425,576460752597474821], fuse=True, remove_duplicate_vertices=True, as_navis=True)
m = m_eb + m_pb

# pen_l3
m_eb = vol_eb.mesh.get(576460753130945957, remove_duplicate_vertices=True, as_navis=True)
m_pb = vol_pb.mesh.get([576460752591088521], fuse=True, remove_duplicate_vertices=True, as_navis=True)

In [ ]:
skel = m.copy() # just in case

# # for neuron in skel:
# #     root_id = str(neuron.id)
# #     sk_row = nametable.loc[nametable['root_ids'].str.contains(root_id)]
# #     name = sk_row['neuron_name'].values[0] if not sk_row.empty else None
# #     skid = sk_row['skid'].values[0] if not sk_row.empty else None
# #     skid = str(int(skid))
    
# #     if not sk_row.empty:
# #         neuron.name = name + '_' + skid
# #         print(neuron.name)
        
# simplify
m_simp = navis.simplify_mesh(skel, 0.3, backend='pyfqmr', inplace=False, parallel=True, progress=True) #lower value, more simple


skel_list = []
# skeletonize
for neuron in m_simp:
    skel = fafbseg.flywire.skeletonize_neuron(neuron) 
    skel_list.append(skel)

skel_list = navis.NeuronList(skel_list)

# then join aka 'heal' unjoined fragments
sk_h_list = []

for idx, neuron in enumerate(skel_list, start=1):
    if len(neuron.root) > 1: # number of disconnected fragments
        skel_h = navis.heal_skeleton(neuron)
        skel_h.soma = None
        sk_h_list.append(skel_h)
        print(f'\r{idx}/{len(skel_list)} skeleton healed')
        sys.stdout.flush()

sk_h_list = navis.NeuronList(sk_h_list)

sk_h_list

In [ ]:
fig=navis.plot3d([sk_h_list[0], sk_h_list[1]], radius=True)

In [16]:
for idx, neuron in enumerate(sk_h_list, start=1):
    neuron.nodes['radius'] = neuron.nodes['radius'].replace(0, 50) # smallest node size shouldn't be 0. 50 is arbitrary

# for idx, neuron in enumerate(sk_h_list, start=1):
#     count += 1
#     neuron.name = f"EPG_L3_{count}"

for idx, neuron in enumerate(sk_h_list, start=1):
    neuron.name = "EPG_LZ_L3_ID_SH"

# downsample neurons to make upload to catmaid quicker
skel_ds = []

for neuron in sk_h_list:
    n_ds = navis.downsample_neuron(neuron, downsampling_factor=1.5, inplace=False)
    skel_ds.append(n_ds)

In [ ]:
fig=navis.plot3d([skel_ds[0], skel_ds[1]], radius=True)

In [21]:
# for neuron in skel_ds:
#     pymaid.upload_neuron(neuron, import_connectors=False, remote_instance=megalopta_flywire)

for neuron in sk_h_list:
    pymaid.upload_neuron(neuron, import_connectors=False, remote_instance=megalopta_flywire)

### full neuron list upload

In [10]:
m

,type,name,id,units,n_vertices,n_faces
0,navis.MeshNeuron,None,576460752943174870,1 nanometer,487460,971865
1,navis.MeshNeuron,None,576460753001015108,1 nanometer,399522,800004
...,...,...,...,...,...,...
16,navis.MeshNeuron,None,576460753031772744,1 nanometer,840699,1681072
17,navis.MeshNeuron,None,576460753128778871,1 nanometer,527049,1055452

In [9]:
m.name

array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [11]:
skel = m.copy() 

for neuron in skel:
    root_id = str(neuron.id)
    sk_row = nametable.loc[nametable['root_ids'].str.contains(root_id)]
    name = sk_row['neuron_name'].values[0] if not sk_row.empty else None
    skid = sk_row['skid'].values[0] if not sk_row.empty else None
    skid = str(int(skid))
    
    if not sk_row.empty:
        neuron.name = name + '_' + skid 
        print(neuron.name)

ER_TL_L_MBUv_SH_ES_14_125261
ER_TL_L_MBUv_SH_ES_10_125025
ER_TL_L_MBUv_SH_ES_18_125035
ER_TL_L_MBUv_SH_ES_19_125041
ER_TL_L_MBUv_SH_ES_21_125099
ER_TL_L_MBUv_SH_ES_23_125194
ER_TL_L_MBUv_SH_ES_24_125199
ER_TL_L_MBUv_SH_ES_27_125291
ER_TL_R_LAL_SH_MS_47232
ER_TL_R_LAL_SH_MS_57041
ER_TL_R_MBUd_ES_26_SH_compl_syn_184355
ER_TL_R_MBUd_ES_42_syn_189306
ER_TL_R_MBUd_SH_MS_62_63046
ER_TL_R_MBUv_01_63126
ER_TL_R_MBUv_02_64133
ER_TL_R_MBUv_SH_ES_21_47185
ER_TL_L_MBUv_SH_ES_22_125189
ER_TL_L_MBUv_SH_ES_25_125250

In [19]:
skel

type              navis.TreeNeuron
name                          None
id              576460752943174870
n_nodes                       9205
n_connectors                  None
n_branches                     306
n_leafs                        420
cable_length        2756174.380258
soma                         10603
units                  1 nanometer
dtype: object

In [21]:
#### SIMPLIFY MESH ####
skel = m.copy()
m_simp = navis.simplify_mesh(skel, 0.3, backend='pyfqmr', inplace=False, parallel=True) #lower value, more simple

Simplifying:   0%|          | 0/18 [00:00<?, ?it/s]

In [22]:
skel_list = []
# skeletonize
for neuron in m_simp:
    skel = fafbseg.flywire.skeletonize_neuron(neuron, dataset=None) 
    skel_list.append(skel)

skel_list = navis.NeuronList(skel_list)

Skeletonizing:   0%|          | 0/141061 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/116152 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/239033 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/152876 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/73517 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/147744 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/152949 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/93646 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/85745 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/91915 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/145038 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/48587 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/57632 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/115453 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/170673 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/258406 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/242118 [00:00<?, ?it/s]

Skeletonizing:   0%|          | 0/153283 [00:00<?, ?it/s]

In [48]:
# if fafbseg.flywire.skeletonize_neuron doesn't work
# import skeletor as sk

# skel_list = []
# # skeletonize
# for neuron in m_simp:
#     fixed = sk.pre.fix_mesh(neuron, remove_disconnected=5, inplace=False)
#     skel = sk.skeletonize.by_wavefront(fixed, waves=1, step_size=1)
#     skel_list.append(skel)

# skel_list = navis.NeuronList(skel_list)

Skeletonizing:   0%|          | 0/246157 [00:00<?, ?it/s]

In [23]:
# then join aka 'heal' unjoined fragments
sk_h_list = []

for idx, neuron in enumerate(skel_list, start=1):
    if len(neuron.root) > 1: # number of disconnected fragments
        skel_h = navis.heal_skeleton(neuron)
        skel_h.soma = None
        sk_h_list.append(skel_h)
        print(f'\r{idx}/{len(skel_list)} skeleton healed')
        sys.stdout.flush()

sk_h_list = navis.NeuronList(sk_h_list)

for idx, neuron in enumerate(sk_h_list, start=1):
    neuron.nodes['radius'] = neuron.nodes['radius'].replace(0, 50) # smallest node size shouldn't be 0. 50 is arbitrary

sk_h_list

1/18 skeleton healed
2/18 skeleton healed
3/18 skeleton healed
4/18 skeleton healed
5/18 skeleton healed
6/18 skeleton healed
7/18 skeleton healed
8/18 skeleton healed
9/18 skeleton healed
10/18 skeleton healed
11/18 skeleton healed
12/18 skeleton healed
13/18 skeleton healed
14/18 skeleton healed
15/18 skeleton healed
16/18 skeleton healed
17/18 skeleton healed
18/18 skeleton healed

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,navis.TreeNeuron,None,576460752943174870,9205,None,383,406,2.793804e+06,None,1 nanometer
1,navis.TreeNeuron,None,576460753001015108,7000,None,334,354,2.098583e+06,None,1 nanometer
...,...,...,...,...,...,...,...,...,...,...
16,navis.TreeNeuron,None,576460753031772744,13517,None,645,691,4.210482e+06,None,1 nanometer
17,navis.TreeNeuron,None,576460753128778871,8623,None,425,463,2.652698e+06,None,1 nanometer

In [ ]:
# check skeletonization results (can use radius=True)
navis.clear3d()
fig=navis.plot3d(skel_list,radius=True)

In [59]:
names = pymaid.get_skids_by_name('/.*glom.*', remote_instance=cat_client)

In [61]:

glom = pymaid.get_neuron(names['skeleton_id'], with_connectors=False, remote_instance=cat_client)

Fetch neurons:   0%|          | 0/176 [00:00<?, ?it/s]

Make nrn:   0%|          | 0/176 [00:00<?, ?it/s]

In [65]:
skid = 184355
er = pymaid.get_neuron(skid, with_connectors=False, remote_instance=cat_client)

In [24]:
name = name.replace("/", "_")

name

'TN_LNO8_todo_AT_SH'

In [24]:
# may need to rename neurons again, not sure why

for neuron in sk_h_list:
    root_id = str(neuron.id)
    sk_row = nametable.loc[nametable['root_ids'].str.contains(root_id)]
    name = sk_row['neuron_name'].values[0] if not sk_row.empty else None
    name = name.replace("/", "_")
    skid = sk_row['skid'].values[0] if not sk_row.empty else None
    skid = str(int(skid))
    
    if not sk_row.empty:
        neuron.name = name + '_' + skid
        print(neuron.name)

sk_h_list

ER_TL_L_MBUv_SH_ES_14_125261
ER_TL_L_MBUv_SH_ES_10_125025
ER_TL_L_MBUv_SH_ES_18_125035
ER_TL_L_MBUv_SH_ES_19_125041
ER_TL_L_MBUv_SH_ES_21_125099
ER_TL_L_MBUv_SH_ES_23_125194
ER_TL_L_MBUv_SH_ES_24_125199
ER_TL_L_MBUv_SH_ES_27_125291
ER_TL_R_LAL_SH_MS_47232
ER_TL_R_LAL_SH_MS_57041
ER_TL_R_MBUd_ES_26_SH_compl_syn_184355
ER_TL_R_MBUd_ES_42_syn_189306
ER_TL_R_MBUd_SH_MS_62_63046
ER_TL_R_MBUv_01_63126
ER_TL_R_MBUv_02_64133
ER_TL_R_MBUv_SH_ES_21_47185
ER_TL_L_MBUv_SH_ES_22_125189
ER_TL_L_MBUv_SH_ES_25_125250

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,navis.TreeNeuron,ER_TL_L_MBUv_SH_ES_14_125261,576460752943174870,9205,None,383,406,2.793804e+06,None,1 nanometer
1,navis.TreeNeuron,ER_TL_L_MBUv_SH_ES_10_125025,576460753001015108,7000,None,334,354,2.098583e+06,None,1 nanometer
...,...,...,...,...,...,...,...,...,...,...
16,navis.TreeNeuron,ER_TL_L_MBUv_SH_ES_22_125189,576460753031772744,13517,None,645,691,4.210482e+06,None,1 nanometer
17,navis.TreeNeuron,ER_TL_L_MBUv_SH_ES_25_125250,576460753128778871,8623,None,425,463,2.652698e+06,None,1 nanometer

In [25]:
pymaid.upload_neuron(sk_h_list, import_connectors=False, remote_instance=megalopta_flywire)

Uploading:   0%|          | 0/18 [00:00<?, ?it/s]

{576460752943174870: {'neuron_id': 463717,
  'skeleton_id': 463716,
  'node_id_map': {1: 8396541,
   10243: 8396542,
   9609: 8396543,
   8243: 8396545,
   7550: 8396547,
   7169: 8396549,
   6960: 8396551,
   6933: 8396553,
   6923: 8396555,
   4631: 8396557,
   4630: 8396559,
   10245: 8396560,
   6153: 8396562,
   5580: 8396564,
   9685: 8396566,
   9684: 8396568,
   5139: 8396569,
   3972: 8396571,
   4634: 8396573,
   4643: 8396575,
   4135: 8396577,
   1871: 8396579,
   3622: 8396581,
   2098: 8396583,
   2091: 8396585,
   2351: 8396587,
   2861: 8396589,
   3265: 8396591,
   3326: 8396593,
   2507: 8396595,
   1818: 8396597,
   1911: 8396599,
   1604: 8396601,
   1307: 8396603,
   1308: 8396605,
   3615: 8396606,
   810: 8396608,
   647: 8396610,
   578: 8396612,
   1077: 8396614,
   36: 8396616,
   70: 8396617,
   71: 8396618,
   73: 8396620,
   74: 8396621,
   72: 8396619,
   76: 8396623,
   93: 8396625,
   96: 8396627,
   79: 8396626,
   80: 8396628,
   130: 8396630,
   77: 8396624,
   99: 8396633,
   84: 8396629,
   85: 8396631,
   90: 8396635,
   87: 8396634,
   101: 8396637,
   116: 8396638,
   94: 8396639,
   88: 8396636,
   86: 8396632,
   75: 8396622,
   102: 8396642,
   106: 8396643,
   97: 8396640,
   104: 8396645,
   111: 8396646,
   112: 8396648,
   98: 8396641,
   107: 8396650,
   103: 8396644,
   119: 8396652,
   108: 8396647,
   150: 8396655,
   109: 8396649,
   123: 8396657,
   114: 8396653,
   115: 8396654,
   137: 8396660,
   146: 8396661,
   122: 8396659,
   149: 8396664,
   120: 8396658,
   117: 8396666,
   134: 8396668,
   118: 8396656,
   141: 8396671,
   124: 8396662,
   139: 8396673,
   148: 8396675,
   136: 8396672,
   138: 8396674,
   143: 8396677,
   144: 8396679,
   133: 8396669,
   145: 8396680,
   140: 8396676,
   157: 8396681,
   158: 8396682,
   160: 8396683,
   155: 8396684,
   125: 8396663,
   132: 8396667,
   161: 8396688,
   162: 8396689,
   131: 8396665,
   151: 8396685,
   170: 8396691,
   142: 8396678,
   220: 8396693,
   113: 8396651,
   166: 8396694,
   135: 8396670,
   156: 8396690,
   153: 8396687,
   159: 8396692,
   164: 8396696,
   163: 8396695,
   179: 8396700,
   152: 8396686,
   168: 8396699,
   198: 8396703,
   199: 8396705,
   200: 8396706,
   201: 8396707,
   167: 8396698,
   173: 8396702,
   165: 8396697,
   197: 8396711,
   174: 8396704,
   176: 8396709,
   175: 8396708,
   189: 8396715,
   181: 8396712,
   209: 8396718,
   183: 8396713,
   171: 8396701,
   169: 8396721,
   177: 8396710,
   180: 8396724,
   188: 8396719,
   187: 8396717,
   207: 8396727,
   185: 8396716,
   203: 8396728,
   205: 8396729,
   217: 8396730,
   223: 8396731,
   196: 8396726,
   222: 8396733,
   192: 8396722,
   194: 8396723,
   211: 8396735,
   212: 8396737,
   213: 8396738,
   214: 8396739,
   215: 8396740,
   195: 8396725,
   191: 8396720,
   235: 8396743,
   230: 8396744,
   229: 8396745,
   210: 8396736,
   208: 8396734,
   184: 8396714,
   206: 8396732,
   231: 8396749,
   237: 8396750,
   240: 8396751,
   234: 8396752,
   226: 8396747,
   238: 8396754,
   218: 8396742,
   242: 8396756,
   216: 8396741,
   228: 8396748,
   232: 8396753,
   246: 8396759,
   225: 8396746,
   236: 8396755,
   259: 8396762,
   239: 8396757,
   249: 8396764,
   256: 8396766,
   248: 8396765,
   255: 8396768,
   257: 8396770,
   253: 8396771,
   258: 8396772,
   274: 8396773,
   263: 8396774,
   269: 8396775,
   251: 8396769,
   264: 8396777,
   275: 8396778,
   250: 8396767,
   245: 8396761,
   244: 8396760,
   284: 8396782,
   247: 8396763,
   261: 8396776,
   281: 8396785,
   273: 8396784,
   241: 8396758,
   317: 8396787,
   265: 8396779,
   270: 8396783,
   295: 8396791,
   276: 8396786,
   277: 8396788,
   291: 8396793,
   268: 8396781,
   279: 8396790,
   266: 8396780,
   392: 8396797,
   309: 8396798,
   283: 8396792,
   300: 8396800,
   286: 8396794,
   307: 8396803,
   293: 8396801,
   316: 8396805,
   288: 8396795,
   297: 8396806,
   301: 8396809,
   305: 8396810,
   296: 8396804,
   315: 8396812,
   298: 8396807,
   299: 8396808,
   320: 8396815,
   331: 8396816,
   318: 8396817,
   303: 8396813,
   294: 8396802,
   278: 8396789,
   310: 8396818,
   313: 8396821,
   326: 8396822,
   323: 8396823,
   302: 8396811,
   292: 8396799,
   373: 8396825,
   312: 8396820,
   311: 8396819,
   321: 8396824,
   306: 8396814,
   325: 8396827,
   348: 8396831,
   334: 8396832,
   324: 8396826,
   341: 8396835,
   382: 8396837,
   340: 8396838,
   332: 8396833,
   352: 8396841,
   367: 8396843,
   349: 8396844,
   343: 8396845,
   339: 8396842,
   360: 8396847,
   329: 8396829,
   330: 8396830,
   356: 8396850,
   355: 8396852,
   389: 8396854,
   336: 8396839,
   358: 8396856,
   369: 8396857,
   362: 8396858,
   357: 8396859,
   346: 8396848,
   371: 8396861,
   350: 8396851,
   54: 8396862,
   383: 8396864,
   347: 8396849,
   342: 8396846,
   366: 8396867,
   361: 8396863,
   337: 8396840,
   390: 8396869,
   333: 8396834,
   385: 8396871,
   359: 8396860,
   354: 8396855,
   351: 8396853,
   406: 8396874,
   364: 8396866,
   372: 8396873,
   384: 8396877,
   375: 8396876,
   374: 8396875,
   395: 8396881,
   379: 8396882,
   327: 8396828,
   425: 8396885,
   335: 8396836,
   380: 8396883,
   399: 8396886,
   365: 8396868,
   393: 8396887,
   376: 8396878,
   398: 8396890,
   414: 8396891,
   377: 8396879,
   430: 8396893,
   289: 8396796,
   386: 8396888,
   370: 8396872,
   420: 8396895,
   409: 8396896,
   368: 8396870,
   388: 8396889,
   363: 8396865,
   403: 8396898,
   432: 8396900,
   378: 8396880,
   402: 8396902,
   396: 8396894,
   391: 8396892,
   437: 8396906,
   401: 8396907,
   381: 8396884,
   405: 8396910,
   404: 8396899,
   445: 8396913,
   411: 8396903,
   410: 8396901,
   400: 8396897,
   421: 8396914,
   439: 8396918,
   424: 8396917,
   413: 8396905,
   426: 8396919,
   473: 8396922,
   422: 8396915,
   465: 8396924,
   423: 8396916,
   431: 8396923,
   428: 8396920,
   419: 8396912,
   447: 8396929,
   429: 8396921,
   418: 8396911,
   438: 8396930,
   433: 8396925,
   478: 8396934,
   440: 8396935,
   444: 8396933,
   471: 8396937,
   446: 8396936,
   434: 8396926,
   470: 8396941,
   459: 8396943,
   412: 8396904,
   479: 8396946,
   435: 8396927,
   481: 8396949,
   463: 8396950,
   460: 8396951,
   436: 8396928,
   466: 8396954,
   442: 8396932,
   484: 8396956,
   448: 8396938,
   416: 8396908,
   417: 8396909,
   461: 8396952,
   486: 8396959,
   450: 8396940,
   559: 8396961,
   557: 8396962,
   503: 8396964,
   499: 8396965,
   455: 8396945,
   469: 8396958,
   494: 8396967,
   456: 8396947,
   493: 8396969,
   511: 8396970,
   472: 8396960,
   449: 8396939,
   464: 8396955,
   458: 8396948,
   536: 8396975,
   507: 8396976,
   482: 8396968,
   462: 8396953,
   480: 8396966,
   487: 8396971,
   527: 8396981,
   526: 8396982,
   452: 8396942,
   453: 8396944,
   488: 8396972,
   476: 8396963,
   500: 8396983,
   515: 8396986,
   506: 8396985,
   495: 8396977,
   537: 8396989,
   498: 8396980,
   513: 8396991,
   532: 8396993,
   512: 8396990,
   468: 8396957,
   454: 8396996,
   555: 8396998,
   543: 8397000,
   491: 8396974,
   542: 8397003,
   441: 8396931,
   567: 8397005,
   516: 8396994,
   504: 8396984,
   510: 8396988,
   514: 8396992,
   490: 8396973,
   517: 8396995,
   547: 8397011,
   552: 8397012,
   551: 8397013,
   520: 8396999,
   540: 8397015,
   521: 8397001,
   538: 8397014,
   497: 8396979,
   528: 8397006,
   525: 8397004,
   563: 8397020,
   534: 8397021,
   556: 8397022,
   531: 8397008,
   518: 8396997,
   577: 8397024,
   570: 8397025,
   568: 8397026,
   566: 8397027,
   597: 8397028,
   562: 8397029,
   575: 8397031,
   579: 8397032,
   560: 8397030,
   554: 8397023,
   565: 8397033,
   592: 8397034,
   561: 8397035,
   546: 8397019,
   545: 8397018,
   496: 8396978,
   535: 8397010,
   599: 8397039,
   544: 8397017,
   68: 8396613,
   598: 8397041,
   67: 8397042,
   529: 8397007,
   522: 8397002,
   508: 8396987,
   533: 8397009,
   574: 8397038,
   571: 8397036,
   573: 8397037,
   606: 8397050,
   576: 8397040,
   582: 8397045,
   612: 8397053,
   608: 8397054,
   622: 8397055,
   586: 8397047,
   541: 8397016,
   588: 8397049,
   600: 8397056,
   580: 8397043,
   587: 8397048,
   621: 8397062,
   611: 8397063,
   610: 8397065,
   620: 8397066,
   596: 8397052,
   492: 8397068,
   679: 8397069,
   672: 8397070,
   626: 8397071,
   602: 8397058,
   613: 8397072,
   636: 8397075,
   617: 8397076,
   583: 8397046,
   641: 8397079,
   642: 8397080,
   651: 8397081,
   614: 8397073,
   581: 8397044,
   654: 8397084,
   607: 8397064,
   609: 8397067,
   615: 8397074,
   624: 8397082,
   637: 8397089,
   603: 8397059,
   630: 8397087,
   618: 8397077,
   631: 8397088,
   601: 8397057,
   695: 8397094,
   677: 8397095,
   605: 8397061,
   648: 8397097,
   66: 8396611,
   655: 8397099,
   680: 8397100,
   628: 8397085,
   708: 8397103,
   629: 8397086,
   645: 8397098,
   671: 8397105,
   650: 8397102,
   634: 8397091,
   604: 8397060,
   653: 8397104,
   638: 8397092,
   632: 8397090,
   619: 8397078,
   718: 8397113,
   595: 8397051,
   681: 8397116,
   699: 8397117,
   649: 8397101,
   625: 8397083,
   694: 8397120,
   703: 8397121,
   721: 8397122,
   696: 8397123,
   664: 8397111,
   660: 8397109,
   690: 8397126,
   667: 8397115,
   666: 8397114,
   675: 8397118,
   713: 8397129,
   728: 8397130,
   720: 8397131,
   644: 8397096,
   656: 8397106,
   750: 8397134,
   640: 8397093,
   686: 8397136,
   657: 8397107,
   722: 8397139,
   693: 8397128,
   719: 8397141,
   701: 8397137,
   734: 8397144,
   685: 8397124,
   711: 8397146,
   723: 8397148,
   704: 8397140,
   736: 8397150,
   689: 8397127,
   659: 8397108,
   739: 8397153,
   661: 8397110,
   710: 8397147,
   787: 8397156,
   741: 8397157,
   775: 8397158,
   712: 8397149,
   706: 8397142,
   727: 8397159,
   676: 8397119,
   665: 8397112,
   737: 8397163,
   773: 8397164,
   698: 8397133,
   738: 8397166,
   726: 8397162,
   724: 8397160,
   751: 8397170,
   740: 8397171,
   716: 8397154,
   747: 8397172,
   757: 8397173,
   755: 8397174,
   761: 8397175,
   745: 8397176,
   802: 8397178,
   733: 8397169,
   714: 8397151,
   702: 8397138,
   709: 8397145,
   784: 8397182,
   758: 8397183,
   744: 8397179,
   863: 8397185,
   742: 8397177,
   752: 8397184,
   754: 8397186,
   732: 8397168,
   687: 8397125,
   778: 8397188,
   730: 8397167,
   700: 8397135,
   749: 8397181,
   697: 8397132,
   717: 8397155,
   691: 8397194,
   799: 8397196,
   715: 8397152,
   832: 8397199,
   762: 8397189,
   791: 8397201,
   768: 8397195,
   770: 8397197,
   796: 8397203,
   748: 8397180,
   707: 8397143,
   794: 8397206,
   764: 8397191,
   777: 8397205,
   763: 8397190,
   725: 8397161,
   806: 8397211,
   774: 8397202,
   834: 8397213,
   766: 8397192,
   776: 8397204,
   821: 8397216,
   767: 8397193,
   772: 8397200,
   824: 8397219,
   780: 8397208,
   842: 8397221,
   779: 8397207,
   65: 8396609,
   785: 8397212,
   818: 8397223,
   840: 8397225,
   795: 8397220,
   789: 8397214,
   849: 8397228,
   800: 8397222,
   782: 8397210,
   833: 8397231,
   781: 8397209,
   793: 8397218,
   792: 8397217,
   790: 8397215,
   804: 8397226,
   817: 8397237,
   808: 8397229,
   888: 8397239,
   729: 8397165,
   813: 8397233,
   872: 8397242,
   801: 8397224,
   771: 8397198,
   841: 8397245,
   919: 8397246,
   827: 8397243,
   823: 8397241,
   64: 8397249,
   851: 8397251,
   805: 8397227,
   843: 8397253,
   846: 8397254,
   891: 8397255,
   859: 8397256,
   816: 8397236,
   869: 8397258,
   853: 8397259,
   887: 8397261,
   814: 8397234,
   759: 8397187,
   837: 8397250,
   861: 8397264,
   820: 8397238,
   844: 8397266,
   847: 8397260,
   836: 8397248,
   812: 8397232,
   878: 8397271,
   856: 8397268,
   870: 8397273,
   860: 8397272,
   835: 8397247,
   879: 8397276,
   899: 8397277,
   809: 8397230,
   838: 8397252,
   883: 8397280,
   864: 8397275,
   881: 8397283,
   875: 8397281,
   877: 8397282,
   862: 8397274,
   855: 8397267,
   854: 8397265,
   904: 8397285,
   929: 8397286,
   857: 8397269,
   915: 8397288,
   850: 8397262,
   852: 8397263,
   895: 8397291,
   918: 8397293,
   845: 8397257,
   873: 8397278,
   922: 8397296,
   858: 8397270,
   905: 8397298,
   894: 8397292,
   914: 8397301,
   893: 8397290,
   911: 8397303,
   913: 8397304,
   1008: 8397305,
   1009: 8397307,
   874: 8397279,
   906: 8397306,
   907: 8397308,
   886: 8397284,
   908: 8397309,
   885: 8397312,
   944: 8397313,
   971: 8397314,
   896: 8397315,
   902: 8397300,
   901: 8397299,
   939: 8397318,
   982: 8397319,
   923: 8397320,
   815: 8397235,
   957: 8397323,
   928: 8397324,
   900: 8397297,
   898: 8397295,
   965: 8397327,
   910: 8397311,
   954: 8397330,
   897: 8397294,
   890: 8397287,
   892: 8397289,
   924: 8397325,
   927: 8397329,
   1071: 8397336,
   962: 8397338,
   943: 8397339,
   947: 8397341,
   921: 8397322,
   920: 8397321,
   949: 8397344,
   938: 8397337,
   903: 8397302,
   932: 8397347,
   1079: 8397348,
   976: 8397349,
   925: 8397326,
   945: 8397345,
   917: 8397317,
   980: 8397353,
   930: 8397331,
   909: 8397310,
   979: 8397356,
   933: 8397333,
   936: 8397335,
   951: 8397351,
   934: 8397334,
   993: 8397361,
   942: 8397343,
   974: 8397363,
   916: 8397316,
   946: 8397346,
   940: 8397340,
   955: 8397354,
   1011: 8397369,
   931: 8397332,
   1004: 8397371,
   960: 8397359,
   984: 8397373,
   941: 8397342,
   964: 8397364,
   1016: 8397376,
   1015: 8397377,
   1013: 8397378,
   1104: 8397379,
   978: 8397375,
   996: 8397381,
   961: 8397360,
   969: 8397367,
   953: 8397352,
   975: 8397372,
   963: 8397362,
   950: 8397350,
   968: 8397366,
   1031: 8397389,
   988: 8397385,
   958: 8397357,
   1048: 8397392,
   959: 8397358,
   831: 8397244,
   989: 8397386,
   966: 8397365,
   972: 8397397,
   994: 8397390,
   983: 8397380,
   985: 8397382,
   973: 8397370,
   1024: 8397402,
   1059: 8397403,
   926: 8397328,
   1114: 8397405,
   977: 8397374,
   935: 8397407,
   1072: 8397408,
   1065: 8397409,
   992: 8397388,
   1017: 8397410,
   1000: 8397395,
   1001: 8397396,
   1003: 8397398,
   1051: 8397414,
   1040: 8397415,
   1025: 8397416,
   1006: 8397400,
   1108: 8397419,
   1067: 8397421,
   1068: 8397422,
   1115: 8397423,
   1026: 8397425,
   991: 8397427,
   998: 8397393,
   990: 8397387,
   1049: 8397431,
   1062: 8397432,
   970: 8397368,
   987: 8397384,
   1020: 8397412,
   1022: 8397413,
   1042: 8397433,
   1027: 8397417,
   1028: 8397418,
   1095: 8397439,
   1070: 8397440,
   1019: 8397411,
   1030: 8397420,
   995: 8397391,
   1038: 8397429,
   1007: 8397401,
   1097: 8397447,
   1012: 8397406,
   999: 8397394,
   1131: 8397450,
   1046: 8397437,
   1119: 8397452,
   1060: 8397445,
   1052: 8397441,
   1066: 8397451,
   1123: 8397454,
   1117: 8397455,
   1076: 8397456,
   1039: 8397430,
   1073: 8397457,
   1111: 8397460,
   1136: 8397461,
   69: 8396615,
   1112: 8397462,
   1055: 8397464,
   1098: 8397466,
   1045: 8397436,
   1043: 8397434,
   1092: 8397470,
   956: 8397355,
   1075: 8397459,
   1085: 8397467,
   1106: 8397474,
   55: 8397476,
   1035: 8397426,
   1036: 8397428,
   1032: 8397424,
   1148: 8397478,
   1053: 8397442,
   1091: 8397473,
   1153: 8397480,
   1074: 8397458,
   1047: 8397438,
   1134: 8397483,
   1054: 8397443,
   1093: 8397475,
   1158: 8397486,
   1069: 8397453,
   1135: 8397488,
   1061: 8397446,
   1084: 8397465,
   1082: 8397463,
   1125: 8397491,
   1100: 8397482,
   1165: 8397492,
   1010: 8397404,
   986: 8397383,
   1151: 8397493,
   1088: 8397471,
   1129: 8397495,
   1110: 8397490,
   1094: 8397477,
   1044: 8397435,
   1152: 8397499,
   1101: 8397484,
   1118: 8397494,
   1124: 8397500,
   1096: 8397479,
   1126: 8397501,
   1063: 8397448,
   1137: 8397504,
   1099: 8397481,
   1120: 8397496,
   1121: 8397497,
   1167: 8397507,
   1160: 8397508,
   1166: 8397509,
   1089: 8397472,
   1056: 8397444,
   1109: 8397489,
   1087: 8397469,
   1064: 8397449,
   1107: 8397487,
   1130: 8397503,
   1209: 8397517,
   1181: 8397518,
   1005: 8397399,
   1150: 8397520,
   1149: 8397519,
   1168: 8397521,
   1162: 8397522,
   1086: 8397468,
   1103: 8397485,
   1189: 8397525,
   1173: 8397526,
   1171: 8397527,
   1127: 8397502,
   1132: 8397505,
   1183: 8397530,
   1202: 8397531,
   1201: 8397532,
   1175: 8397533,
   1192: 8397534,
   1139: 8397510,
   1122: 8397498,
   1187: 8397537,
   1188: 8397538,
   1157: 8397539,
   1133: 8397506,
   1230: 8397541,
   1140: 8397511,
   1145: 8397515,
   1216: 8397544,
   1141: 8397512,
   1249: 8397546,
   1199: 8397547,
   1269: 8397548,
   1246: 8397549,
   1161: 8397528,
   1146: 8397516,
   1234: 8397552,
   1367: 8397553,
   822: 8397240,
   1197: 8397556,
   1195: 8397555,
   1247: 8397558,
   1193: 8397554,
   1212: 8397559,
   1210: 8397560,
   1261: 8397562,
   1217: 8397563,
   1223: 8397564,
   1155: 8397524,
   1142: 8397513,
   1174: 8397540,
   1164: 8397529,
   1242: 8397570,
   61: 8397571,
   1176: 8397572,
   1233: 8397574,
   1154: 8397523,
   1169: 8397535,
   1224: 8397577,
   1237: 8397578,
   1226: 8397579,
   1200: 8397561,
   1213: 8397582,
   1191: 8397551,
   1231: 8397585,
   1219: 8397581,
   1204: 8397566,
   1264: 8397587,
   1143: 8397514,
   1245: 8397589,
   ...}},
 576460753001015108: {'neuron_id': 463722,
  'skeleton_id': 463721,
  'node_id_map': {1: 8405746,
   8230: 8405747,
   6788: 8405748,
   6630: 8405750,
   6403: 8405752,
   5573: 8405754,
   5481: 8405756,
   8068: 8405758,
   5136: 8405760,
   4679: 8405762,
   4470: 8405764,
   4261: 8405766,
   4314: 8405768,
   5197: 8405770,
   4988: 8405772,
   4251: 8405774,
   7000: 8405776,
   4217: 8405778,
   4216: 8405780,
   3361: 8405781,
   3154: 8405783,
   3243: 8405785,
   2590: 8405787,
   2084: 8405789,
   2081: 8405791,
   2093: 8405793,
   2082: 8405795,
   4126: 8405797,
   1426: 8405799,
   3612: 8405801,
   1579: 8405803,
   405: 8405805,
   433: 8405807,
   556: 8405809,
   171: 8405811,
   1063: 8405813,
   1062: 8405815,
   11: 8405817,
   55: 8405818,
   59: 8405820,
   56: 8405819,
   64: 8405822,
   62: 8405823,
   57: 8405821,
   58: 8405825,
   67: 8405826,
   72: 8405827,
   70: 8405829,
   75: 8405830,
   60: 8405824,
   73: 8405832,
   65: 8405828,
   71: 8405831,
   74: 8405833,
   76: 8405834,
   86: 8405836,
   82: 8405838,
   79: 8405837,
   90: 8405841,
   81: 8405840,
   77: 8405835,
   80: 8405839,
   89: 8405844,
   78: 8405846,
   93: 8405847,
   83: 8405842,
   87: 8405845,
   84: 8405843,
   118: 8405850,
   91: 8405848,
   98: 8405852,
   101: 8405854,
   100: 8405856,
   103: 8405858,
   102: 8405859,
   95: 8405851,
   104: 8405860,
   96: 8405853,
   97: 8405855,
   99: 8405857,
   108: 8405862,
   107: 8405861,
   112: 8405865,
   111: 8405864,
   110: 8405863,
   114: 8405866,
   113: 8405869,
   94: 8405849,
   115: 8405867,
   117: 8405868,
   122: 8405870,
   123: 8405871,
   124: 8405872,
   125: 8405873,
   128: 8405875,
   127: 8405874,
   132: 8405876,
   133: 8405877,
   135: 8405879,
   136: 8405880,
   134: 8405878,
   137: 8405881,
   138: 8405882,
   139: 8405883,
   158: 8405887,
   144: 8405888,
   154: 8405890,
   146: 8405889,
   140: 8405884,
   141: 8405885,
   153: 8405895,
   168: 8405896,
   150: 8405894,
   148: 8405892,
   162: 8405900,
   151: 8405901,
   147: 8405891,
   142: 8405886,
   167: 8405904,
   156: 8405898,
   149: 8405893,
   172: 8405907,
   170: 8405908,
   180: 8405909,
   240: 8405910,
   241: 8405911,
   49: 8405812,
   155: 8405897,
   163: 8405905,
   212: 8405914,
   184: 8405916,
   186: 8405917,
   182: 8405918,
   190: 8405920,
   207: 8405921,
   174: 8405912,
   183: 8405919,
   178: 8405913,
   179: 8405915,
   223: 8405925,
   192: 8405926,
   194: 8405928,
   161: 8405903,
   213: 8405930,
   205: 8405931,
   181: 8405933,
   157: 8405899,
   191: 8405927,
   159: 8405902,
   219: 8405937,
   165: 8405906,
   187: 8405922,
   238: 8405940,
   199: 8405932,
   202: 8405935,

### figure plots

In [20]:
sk_h_list

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,navis.TreeNeuron,TN_LNO1_R_SH_AT_47215_NO,504403158488287832,32335,None,2627,2933,9.376130e+06,None,1 nanometer
1,navis.TreeNeuron,TN_LNO2_R_SH_AT_47221_NO,504403158401056605,37817,None,3095,3440,1.135861e+07,None,1 nanometer
...,...,...,...,...,...,...,...,...,...,...
4,navis.TreeNeuron,TN/LNO7_todo_AT_SH_57076_NO,504403158402520236,13481,None,1342,1609,4.480783e+06,None,1 nanometer
5,navis.TreeNeuron,TN/LNO8_todo_AT_SH_57081_NO,504403158268845171,9274,None,1046,1304,3.220265e+06,None,1 nanometer

In [27]:
# save meshes locally...
# navis.write_mesh(sk_h_list, './hd_neurons/raw_neuron_meshes/NO/{neuron.name}.obj', filetype='obj')
navis.write_swc(sk_h_list, './hd_neurons/raw_neuron_meshes/NO/{neuron.name}.swc')

Writing:   0%|          | 0/6 [00:00<?, ?it/s]

In [20]:
m = vol_eb.mesh.get(EPG_L3, remove_duplicate_vertices=True, as_navis=True)

for neuron in m:
    root_id = str(neuron.id)
    sk_row = nametable.loc[nametable['root_ids'].str.contains(root_id)]
    name = sk_row['neuron_name'].values[0] if not sk_row.empty else None
    skid = sk_row['skid'].values[0] if not sk_row.empty else None
    skid = str(int(skid))
    
    if not sk_row.empty:
        neuron.name = name + '_' + skid + '_' + 'EB'
        print(neuron.name)

navis.write_mesh(m, './hd_neurons/raw_neuron_meshes/EB/{neuron.name}.obj', filetype='obj')

EPG_LZ_L3_ID_SH_54939_EB

Writing:   0%|          | 0/1 [00:00<?, ?it/s]

In [21]:
m

,type,name,id,units,n_vertices,n_faces
0,navis.MeshNeuron,EPG_LZ_L3_ID_SH_54939_EB,576460753102309773,1 nanometer,1098485,2196365

In [23]:
skid = 54939
cat_list = pymaid.get_neuron(skid, with_connectors=False, remote_instance=cat_client)

cat_n = cat_list.copy()
match = re.search(r'^([A-Z]{3}).*?([LR]\d)', cat_n.name)
if match:
    extracted = f"{match.group(1)}_{match.group(2)}"
    cat_n.name = extracted + '_' + cat_n.id + '_' + 'backbone'
    print(cat_n.name)
else:
    print(f"Original: {cat_n.name} → No match found")


cat_n

INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)
INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)

EPG_L3_54939_backbone

type                    CatmaidNeuron
name            EPG_L3_54939_backbone
id                              54939
n_nodes                          1425
n_connectors                        0
n_branches                         80
n_leafs                            86
cable_length               1243720.25
soma                             None
units                     1 nanometer
dtype: object

In [40]:
#### SIMPLIFY MESH ####
m_simp = navis.simplify_mesh(sk_h_list, 0.5, backend='pyfqmr', inplace=False, parallel=True) #lower value, more simple

Simplifying:   0%|          | 0/19 [00:00<?, ?it/s]

In [41]:
# save meshes locally...
navis.write_mesh(m_simp, './hd_neurons/simplified_neuron_meshes/{neuron.name}.obj', filetype='obj')

Writing:   0%|          | 0/19 [00:00<?, ?it/s]

In [85]:
 # When reading all files in folder you have to specificy the file extension (e.g. *.stl)
 meshes = navis.read_mesh('./hd_neurons/simplified_neuron_meshes/*.obj')

Importing:   0%|          | 0/19 [00:00<?, ?it/s]

In [ ]:
# Load a mesh file into a Volume
# vol = navis.read_mesh('test_mesh.stl', output='volume')

In [10]:
# get EB and PB volumes from Megalopta dataset 
eb_m = pymaid.get_volume(['EB'], remote_instance=cat_client)
pb_m = pymaid.get_volume(['PB_new'], remote_instance=cat_client)

INFO  : Cached data used. Use `pymaid.clear_cache()` to clear. (pymaid)

In [60]:
eb_m.color = (0, 0, 0, .02)
pb_m.color = (0, 0, 0, .02)

In [64]:
skid_list = nametable['skid'].to_list()

cat_list = []

for skid in skid_list:
    cat_n = pymaid.get_neuron(skid, with_connectors=False, remote_instance=cat_client)
    cat_list.append(cat_n)

cat_list = navis.NeuronList(cat_list)

cat_list

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,CatmaidNeuron,EPG_LZ_L2_2_SH_HH_MS,55944,19441,0,1478,1547,7088621.0,None,1 nanometer
1,CatmaidNeuron,EPG_LZ_L2_3_SH_MS_HH,55952,16741,0,1141,1190,6062857.0,None,1 nanometer
...,...,...,...,...,...,...,...,...,...,...
21,CatmaidNeuron,PEN_RW_R9_SH_MT5,64257,4557,0,273,288,2240929.0,None,1 nanometer
22,CatmaidNeuron,PEN_LY_L4_SH_SB_cina,99084,2529,0,163,172,1551647.5,None,1 nanometer

In [96]:
EPG_R1_sk = cat_list[10:13]

In [ ]:
# Convert to Pandas Series to use .str.contains()
EPG_R1 = pd.Series(meshes.name).str.contains('R1')
EPG_R1 = meshes[EPG_R1]
EPG_R1

In [102]:
EPG_R1_sk.color = (0.1, 0.1, 0.1)
# color={EPG_R1_sk[0]: (65, 65, b), ...}

In [101]:
EPG_R1_sk.color

(65, 65, 65)

In [ ]:
EPG_R1_sk

In [ ]:
#to do: set neuron-color dict using navis default colors

In [108]:
navis.clear3d()
navis.plot3d([[EPG_R1[0], EPG_R1_sk[0], eb_m]], color={EPG_R1_sk[0]: (0.1,0.1,0.1)}, backend='k3d', inline=False)

INFO  : Use the `.display()` method to show the plot. (navis)

Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, axes_helper_colors=[16711680, 65280, 255], background…

In [ ]:
# Clear previous plots
navis.clear3d()

# Step 1: Adjust the opacity of the brain volume.
# Increase opacity from 0.02 to 0.2 for visibility.
eb_m.color = (0, 0, 0, 0.03)

# Step 2: Plot the neurons and the brain volume using the plotly backend.
# Note: We use a nested list to group objects. Adjust this structure if needed.
fig = navis.plot3d([eb_m], backend='plotly', inline=False)

# Step 3: Update the figure layout:
# - Set an explicit title.
# - Update the camera to use an orthographic projection and control orientation.
fig.update_layout(
    title='example',
    scene_camera=dict(
        projection=dict(type='orthographic'),
        eye=dict(x=0.1, y=0.1, z=1.25)
    )
)

for trace in fig.data:
    # Option 1: If the trace name contains 'eb_m', adjust its opacity.
    if hasattr(trace, 'name') and trace.name is not None and 'eb_m' in trace.name:
        trace.opacity = 0.03  # adjust this value as needed

# Step 4: Render the figure.
fig.show()

In [ ]:
# Helper function: Convert navis (r, g, b, a) color tuple to 24-bit hex integer.
def convert_color(color_tuple):
    r, g, b, a = color_tuple
    # Scale values if they are normalized
    if r <= 1.0 and g <= 1.0 and b <= 1.0:
        r = int(r * 255)
        g = int(g * 255)
        b = int(b * 255)
    else:
        r = int(r)
        g = int(g)
        b = int(b)
    return (r << 16) + (g << 8) + b

# Create the k3d plot without width/height arguments.
plot = k3d.plot(camera_auto_fit=False)

# Manually set the camera.
# The camera expects a list of 9 numbers:
# [pos_x, pos_y, pos_z, center_x, center_y, center_z, up_x, up_y, up_z]
# Adjust these values for your desired orientation and zoom.
plot.camera = [0, 0, 300,    # Camera position: 300 units along z-axis
               0, 0, 0,      # Look-at point: the origin
               0, 1, 0]      # Up vector: positive y-axis

# Add neuron meshes to the plot.
# 'meshes' is a navis.NeuronList containing MeshNeuron objects.
for neuron in meshes:
    vertices = neuron.vertices.astype(np.float32)
    faces = neuron.faces.astype(np.uint32)
    
    # If neuron has a color attribute, use it; otherwise default to gray.
    if hasattr(neuron, 'color') and neuron.color is not None:
        color_hex = convert_color(neuron.color)
        opacity = neuron.color[3] if len(neuron.color) >= 4 else 1.0
    else:
        color_hex = 0xAAAAAA
        opacity = 1.0
    
    neuron_mesh = k3d.mesh(vertices, faces, color=color_hex, opacity=opacity)
    plot += neuron_mesh

# Add the brain volume.
# 'eb_m' is a navis.Volume object.
vol_vertices = eb_m.vertices.astype(np.float32)
vol_faces = eb_m.faces.astype(np.uint32)
vol_color = convert_color(eb_m.color)
vol_opacity = 0.05  # Set the desired transparency

volume_mesh = k3d.mesh(vol_vertices, vol_faces, color=vol_color, opacity=vol_opacity)
plot += volume_mesh

# Optionally display the interactive plot to verify the orientation.
plot.display()

# To generate a static 2D screenshot, capture the current view.
#screenshot = plot.get_screenshot()

# Save the screenshot as a PNG file.
#with open('static_view.png', 'wb') as f:
#    f.write(screenshot)

### random

In [29]:
sk_h_list

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,navis.TreeNeuron,EPG_RZ_R1/L1_ID_MS_MT1_64077_EB,576460752963411671,18523,None,1219,1304,4.824662e+06,None,1 nanometer
1,navis.TreeNeuron,EPG_RZ_R1/L1_ID_MT3_64084_EB,576460753015406203,11202,None,800,861,3.042089e+06,None,1 nanometer

In [22]:
navis.write_precomputed(sk_h_list, filepath='./eb_lateral_skeletons/', radius=True)

Writing:   0%|          | 0/19 [00:00<?, ?it/s]

In [28]:
sk_h_list[7].name = 'EPG_RW_R9_MS_EPGt_118347'

In [30]:
navis.write_swc(sk_h_list, './eb_lateral_skeletons/eb_skel.zip')

Writing:   0%|          | 0/19 [00:00<?, ?it/s]

In [6]:
sk_h_list = navis.read_swc('D:/analysis/eb_lateral_skeletons/eb_swc', include_subdirs=True)

Importing:   0%|          | 0/8 [00:00<?, ?it/s]

In [ ]:
pymaid.upload_neuron(sk_h_list, import_connectors=False, remote_instance=megalopta_flywire)

In [11]:
sk_h_list.name

array(['EPG_LZ_L2_1_PEG_ID_SH_MS_HH_55930', 'EPG_LZ_L2_2_SH_HH_MS_55944',
       'EPG_LZ_L2_3_SH_MS_HH_55952', 'EPG_RW_R8_ID_HH_56351',
       'EPG_RW_R8_ID_HH_56356', 'EPG_RW_R8_todo_SH_HH_55936',
       'EPG_RW_R9_ID_SH_64276', 'EPG_RW_R9_MS_EPGt_118347'], dtype='<U33')