In [1]:
import sys
import pandas as pd
import numpy as np
import navis
import pymaid
import random
import re
import ast
import json


import skeletor as sk
import cloudvolume as cv
import fafbseg
import caveclient
import k3d

D:\flywire_backup\cave\cave\lib\site-packages\blessed\terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-color'): Could not find terminal xterm-color
  warnings.warn(msg)

In [20]:
#megalopta project id: 8
#megalopta test project id: 25
#megalopta flywire project id: 28
#eciton CX: 7
path = 'D:/flywire_backup/cave/cat_client.json' # replace with your path

with open(path, 'r') as f:
    conn_file = json.load(f)
api_token = conn_file['api_token']
http_user = conn_file['http_user']
http_password = conn_file['http_password']
server = conn_file['server']

cat_client = pymaid.CatmaidInstance(server = server, 
                                api_token = api_token,
                                caching = True,
                                project_id = 8,
                                http_user = http_user,
                                http_password = http_password 
                                )

client = caveclient.CAVEclient(server_address='https://global.connectomics.braininbrain.org')

client = caveclient.CAVEclient(datastack_name='megalopta_fb_eb_datastack')
auth = client.auth
cg = client.chunkedgraph
print('client set')


################################ other useful functions
# client.info.get_datastacks()
#print(f"My current token is: {auth.token}")

INFO  : Global CATMAID instance set. Caching is ON. (pymaid)

client set

In [4]:
# ngl_segmentation = 'graphene://https://local.cave.braininbrain.org/segmentation/table/heinze_eciton_PB_v1' # obtain from CAVE 
ngl_segmentation = 'graphene://https://local.cave.braininbrain.org/segmentation/table/megalopta_FB_EB_v3'
navis.patch_cloudvolume()
vol = cv.CloudVolume(ngl_segmentation, use_https=True, progress=False)

INFO  : cloud-volume successfully patched! (navis)

In [15]:
# # Example for nueron with a single segment id: PFN_LY_L4_AT_MS_VN2_PFN2E
# pfn1 = [576460752498180584]

# # Example for nueron with two segment ids: PFN_LY_L4_MS_VN3_PFN2E
# pfn2 = [576460752505789669, 576460752436280917]

# namelist = ['PFN_LY_L4_AT_MS_VN2_PFN2E_CAVE', 'PFN_LY_L4_MS_VN3_PFN2E_CAVE']

# pfn1_m = vol.mesh.get(pfn1, remove_duplicate_vertices=True, as_navis=True) # download neuron mesh
# pfn2_m = vol.mesh.get(pfn2, remove_duplicate_vertices=True, fuse=True, allow_missing=True, as_navis=True)

# pfn1_m = navis.NeuronList(pfn1_m)
# pfn2_m = navis.NeuronList(pfn2_m)

# m = pfn1_m + pfn2_m # m = 'mesh'

# for neuron, name in zip(m, namelist): # name the neurons (skids are better)
#     neuron.name = name
    
# m

,type,name,id,units,n_vertices,n_faces
0,navis.MeshNeuron,PFN_LY_L4_AT_MS_VN2_PFN2E_CAVE,576460752498180584,1 nanometer,84701,167237
1,navis.MeshNeuron,PFN_LY_L4_MS_VN3_PFN2E_CAVE,NA,1 nanometer,84395,166800

In [5]:
er = [576460753128455242]
er = vol.mesh.get(er, remove_duplicate_vertices=True, as_navis=True) # download neuron mesh
er = navis.NeuronList(er)

In [6]:
er[0].name = 'ER_L_MBUd_125523'

In [7]:
er

,type,name,id,units,n_vertices,n_faces
0,navis.MeshNeuron,ER_L_MBUd_125523,576460753128455242,1 nanometer,291635,582292

In [8]:
mesh_list = er.copy() # back up just in case
        
# cave meshes are very complex, so simplify
m_simp = navis.simplify_mesh(mesh_list, 0.3, backend='pyfqmr', inplace=False, parallel=True, progress=True) #lower value, more simple

Simplifying:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# preview simplified mesh
fig=navis.plot3d(m_simp)

In [10]:
'''SKELETONIZE 
- this is the tricky part...there are several options to skeletonize the mesh, 
but I haven't solved this. Below typically works for visualization purposes,
but results in spikey, convoluted skeletons that *USUALLY* need to be cleaned before being used for 
morphological analysis (nblast, etc)...however the eciton examples below look quite nice. You might 
be able to use this exactly as is! 

- for more, see https://navis-org.github.io/skeletor/
- see: https://www.caveconnecto.me/pcg_skel/
- see: https://meshparty.readthedocs.io/en/latest/
- play around with: client.skeleton.get_bulk_skeletons()

below uses skeletor:
'''
skel_list = []

for mesh in m_simp:
    sk = navis.skeletonize(mesh)
    skel_list.append(sk)

skel_list = navis.NeuronList(skel_list)

# then join aka 'heal' unjoined fragments
sk_h_list = []

for idx, neuron in enumerate(skel_list, start=1):
    if len(neuron.root) > 1: # number of disconnected fragments
        skel_h = navis.heal_skeleton(neuron)
        skel_h.soma = None
        sk_h_list.append(skel_h)
        print(f'\r{idx}/{len(skel_list)} skeleton healed')
        sys.stdout.flush()

for idx, neuron in enumerate(sk_h_list, start=1):
    neuron.nodes['radius'] = neuron.nodes['radius'].replace(0, 50) # smallest node size shouldn't be 0. 50 is arbitrary

sk_h_list = navis.NeuronList(sk_h_list)

sk_h_list

1/1 skeleton healed

,type,name,id,n_nodes,n_connectors,n_branches,n_leafs,cable_length,soma,units
0,navis.TreeNeuron,ER_L_MBUd_125523,576460753128455242,7543,None,572,630,2.178195e+06,None,1 nanometer

In [ ]:
# preview skeletonized neuron with node radius 
fig=navis.plot3d(sk_h_list, radius=True)

In [ ]:
# preview skeletonized neuron with node radius off 
fig=navis.plot3d(sk_h_list, radius=False)

In [21]:
# Will stop here, but you can then download Eciton catmaid neurons, prune so it's just the main branch:
# mainFiber = navis.longest_neurite(cat_neuron)
# then stich with your skeletonized mesh
# to_stitch = neuron1 + neuron2
# complete_n = navis.stitch_skeletons(to_stitch, method=[0,10], master='LARGEST')

# upload skeletonized neurons to catmaid
pymaid.upload_neuron(sk_h_list, import_connectors=False, remote_instance=cat_client)

Uploading:   0%|          | 0/1 [00:00<?, ?it/s]

{576460753128455242: {'neuron_id': 508950,
  'skeleton_id': 508949,
  'node_id_map': {0: 8861710,
   8323: 8861711,
   8324: 8861712,
   7851: 8861713,
   7877: 8861715,
   8212: 8861717,
   8201: 8861719,
   1: 8861714,
   8108: 8861722,
   7902: 8861724,
   8068: 8861726,
   8067: 8861728,
   8032: 8861729,
   7976: 8861731,
   8121: 8861733,
   8115: 8861735,
   7964: 8861736,
   7963: 8861738,
   7429: 8861739,
   7470: 8861741,
   6491: 8861743,
   6515: 8861745,
   7847: 8861747,
   7841: 8861749,
   7816: 8861751,
   7807: 8861753,
   7837: 8861755,
   7836: 8861757,
   7464: 8861758,
   7714: 8861760,
   7683: 8861762,
   7717: 8861764,
   7682: 8861766,
   7572: 8861768,
   7591: 8861770,
   7546: 8861772,
   7507: 8861774,
   7977: 8861776,
   7402: 8861778,
   7320: 8861780,
   7349: 8861782,
   7350: 8861784,
   7327: 8861785,
   7227: 8861787,
   7242: 8861789,
   7035: 8861791,
   7146: 8861793,
   7180: 8861795,
   7103: 8861797,
   7172: 8861798,
   7096: 8861800,
   7230: 8861802,
   7042: 8861804,
   6967: 8861806,
   6950: 8861808,
   6949: 8861810,
   6920: 8861812,
   6850: 8861814,
   6869: 8861816,
   6868: 8861818,
   6749: 8861819,
   6730: 8861821,
   6990: 8861823,
   6656: 8861825,
   6640: 8861827,
   6607: 8861829,
   6586: 8861830,
   6715: 8861832,
   6626: 8861834,
   6634: 8861836,
   6633: 8861838,
   6631: 8861839,
   6457: 8861840,
   5073: 8861842,
   5064: 8861844,
   6348: 8861846,
   6449: 8861848,
   6388: 8861850,
   6354: 8861852,
   6270: 8861854,
   6312: 8861856,
   6263: 8861858,
   6254: 8861860,
   6253: 8861862,
   6148: 8861863,
   6111: 8861865,
   5636: 8861867,
   8306: 8861869,
   140: 8861871,
   5605: 8861873,
   6029: 8861874,
   6019: 8861876,
   5875: 8861878,
   5743: 8861880,
   5769: 8861882,
   5774: 8861884,
   5764: 8861886,
   5652: 8861888,
   5693: 8861890,
   5640: 8861892,
   5665: 8861894,
   5629: 8861896,
   136: 8861889,
   5646: 8861897,
   5511: 8861899,
   7075: 8861901,
   5573: 8861903,
   5043: 8861905,
   5591: 8861907,
   153: 8861909,
   5401: 8861911,
   5397: 8861913,
   5407: 8861914,
   4966: 8861916,
   5396: 8861918,
   5278: 8861920,
   5000: 8861922,
   5281: 8861924,
   5208: 8861926,
   5211: 8861928,
   5214: 8861930,
   5080: 8861932,
   4928: 8861934,
   4661: 8861936,
   4648: 8861938,
   4649: 8861940,
   5543: 8861941,
   4945: 8861943,
   4919: 8861945,
   4905: 8861947,
   4906: 8861949,
   4836: 8861950,
   176: 8861948,
   4808: 8861953,
   185: 8861955,
   4793: 8861957,
   4788: 8861959,
   4787: 8861960,
   4751: 8861962,
   4759: 8861964,
   4722: 8861966,
   4727: 8861968,
   5604: 8861970,
   4593: 8861972,
   4551: 8861974,
   4543: 8861976,
   211: 8861978,
   4530: 8861980,
   4554: 8861981,
   4512: 8861983,
   4492: 8861985,
   4188: 8861987,
   4173: 8861989,
   4373: 8861991,
   4338: 8861993,
   4337: 8861994,
   4294: 8861995,
   4357: 8861997,
   4308: 8861999,
   4275: 8862001,
   4435: 8862003,
   3570: 8862005,
   2623: 8862007,
   4060: 8862009,
   3997: 8862011,
   4005: 8862013,
   3898: 8862015,
   3827: 8862017,
   3795: 8862019,
   3813: 8862021,
   3808: 8862023,
   3812: 8862025,
   3815: 8862027,
   3825: 8862029,
   3678: 8862031,
   3650: 8862033,
   3687: 8862035,
   3630: 8862037,
   4197: 8862039,
   220: 8862008,
   3508: 8862042,
   3476: 8862044,
   3461: 8862046,
   3444: 8862048,
   3410: 8862050,
   3408: 8862052,
   3343: 8862054,
   3316: 8862056,
   3318: 8862058,
   3253: 8862060,
   3222: 8862062,
   3210: 8862064,
   3144: 8862066,
   3141: 8862068,
   3135: 8862070,
   3134: 8862072,
   3483: 8862073,
   3084: 8862075,
   2862: 8862077,
   2863: 8862079,
   2992: 8862080,
   2940: 8862082,
   2877: 8862084,
   276: 8862086,
   2890: 8862088,
   2873: 8862089,
   2842: 8862091,
   3077: 8862093,
   2856: 8862095,
   2841: 8862097,
   2768: 8862099,
   2686: 8862101,
   3592: 8862103,
   3590: 8862105,
   2565: 8862106,
   891: 8862108,
   2345: 8862110,
   2546: 8862112,
   2464: 8862114,
   2477: 8862116,
   2469: 8862118,
   2302: 8862120,
   2178: 8862122,
   2351: 8862124,
   2270: 8862126,
   2239: 8862128,
   2204: 8862130,
   2197: 8862132,
   2202: 8862133,
   2348: 8862135,
   2134: 8862137,
   1431: 8862139,
   1921: 8862141,
   1903: 8862143,
   1977: 8862145,
   1975: 8862147,
   1865: 8862148,
   1820: 8862150,
   1822: 8862152,
   1857: 8862154,
   1740: 8862156,
   1732: 8862158,
   331: 8862160,
   1703: 8862161,
   329: 8862159,
   1727: 8862163,
   1733: 8862164,
   1671: 8862166,
   1634: 8862168,
   1640: 8862170,
   1429: 8862172,
   1385: 8862174,
   881: 8862176,
   1365: 8862178,
   1368: 8862180,
   1367: 8862182,
   1242: 8862183,
   199: 8861979,
   4555: 8862186,
   1229: 8862187,
   1243: 8862189,
   1244: 8862191,
   1206: 8862192,
   1176: 8862194,
   1135: 8862196,
   1094: 8862198,
   1096: 8862200,
   1065: 8862202,
   985: 8862204,
   984: 8862206,
   938: 8862207,
   906: 8862209,
   861: 8862211,
   838: 8862213,
   1231: 8862215,
   808: 8862217,
   795: 8862219,
   423: 8862221,
   700: 8862223,
   605: 8862225,
   594: 8862227,
   532: 8862229,
   475: 8862231,
   753: 8862233,
   506: 8862235,
   512: 8862237,
   497: 8862239,
   2547: 8862241,
   2548: 8862243,
   509: 8862244,
   455: 8862246,
   370: 8862222,
   195: 8862249,
   389: 8862250,
   390: 8862251,
   392: 8862253,
   391: 8862252,
   393: 8862254,
   395: 8862256,
   394: 8862255,
   396: 8862257,
   397: 8862258,
   398: 8862259,
   399: 8862260,
   400: 8862261,
   401: 8862262,
   403: 8862264,
   402: 8862263,
   404: 8862265,
   412: 8862268,
   405: 8862270,
   408: 8862269,
   406: 8862266,
   407: 8862267,
   413: 8862273,
   409: 8862271,
   410: 8862272,
   415: 8862275,
   416: 8862276,
   414: 8862274,
   417: 8862277,
   418: 8862278,
   421: 8862279,
   422: 8862280,
   425: 8862282,
   432: 8862284,
   367: 8862286,
   428: 8862285,
   448: 8862289,
   427: 8862283,
   424: 8862281,
   431: 8862288,
   445: 8862292,
   430: 8862287,
   388: 8862248,
   433: 8862290,
   434: 8862291,
   437: 8862295,
   438: 8862296,
   429: 8862299,
   452: 8862301,
   443: 8862302,
   442: 8862300,
   458: 8862304,
   436: 8862294,
   387: 8862306,
   441: 8862298,
   435: 8862293,
   440: 8862309,
   439: 8862297,
   446: 8862311,
   386: 8862247,
   444: 8862303,
   447: 8862305,
   449: 8862307,
   451: 8862310,
   457: 8862314,
   454: 8862312,
   450: 8862308,
   456: 8862313,
   461: 8862317,
   459: 8862315,
   465: 8862319,
   463: 8862318,
   385: 8862323,
   460: 8862316,
   494: 8862326,
   473: 8862327,
   483: 8862329,
   477: 8862330,
   474: 8862328,
   468: 8862322,
   467: 8862321,
   466: 8862320,
   485: 8862333,
   469: 8862324,
   486: 8862335,
   488: 8862336,
   484: 8862334,
   495: 8862338,
   496: 8862339,
   478: 8862331,
   479: 8862332,
   471: 8862325,
   470: 8862343,
   487: 8862337,
   538: 8862345,
   502: 8862346,
   489: 8862340,
   492: 8862344,
   491: 8862342,
   381: 8862240,
   490: 8862341,
   511: 8862350,
   514: 8862351,
   501: 8862349,
   379: 8862236,
   500: 8862348,
   498: 8862347,
   384: 8862245,
   380: 8862238,
   540: 8862357,
   377: 8862232,
   526: 8862359,
   521: 8862360,
   533: 8862362,
   382: 8862364,
   549: 8862365,
   503: 8862352,
   517: 8862363,
   529: 8862369,
   507: 8862355,
   520: 8862368,
   518: 8862366,
   519: 8862367,
   513: 8862358,
   515: 8862361,
   523: 8862371,
   504: 8862353,
   536: 8862376,
   510: 8862356,
   524: 8862372,
   375: 8862379,
   557: 8862380,
   531: 8862378,
   571: 8862382,
   528: 8862375,
   579: 8862384,
   580: 8862385,
   530: 8862377,
   522: 8862370,
   541: 8862386,
   550: 8862389,
   505: 8862354,
   553: 8862391,
   537: 8862381,
   545: 8862390,
   573: 8862394,
   542: 8862387,
   559: 8862396,
   564: 8862397,
   554: 8862398,
   525: 8862373,
   575: 8862401,
   563: 8862402,
   546: 8862392,
   578: 8862404,
   543: 8862388,
   548: 8862393,
   555: 8862399,
   562: 8862406,
   560: 8862403,
   527: 8862374,
   566: 8862408,
   558: 8862410,
   567: 8862409,
   556: 8862400,
   589: 8862414,
   539: 8862383,
   581: 8862416,
   565: 8862407,
   376: 8862230,
   592: 8862418,
   572: 8862415,
   561: 8862405,
   582: 8862421,
   620: 8862422,
   586: 8862423,
   593: 8862424,
   569: 8862412,
   574: 8862417,
   568: 8862411,
   552: 8862395,
   601: 8862428,
   577: 8862420,
   618: 8862430,
   603: 8862431,
   576: 8862419,
   584: 8862433,
   583: 8862425,
   585: 8862426,
   608: 8862437,
   590: 8862429,
   606: 8862439,
   599: 8862435,
   598: 8862434,
   595: 8862432,
   610: 8862442,
   374: 8862228,
   616: 8862444,
   373: 8862226,
   570: 8862413,
   604: 8862440,
   587: 8862427,
   631: 8862448,
   636: 8862449,
   588: 8862450,
   626: 8862452,
   612: 8862446,
   372: 8862454,
   609: 8862443,
   600: 8862436,
   611: 8862445,
   635: 8862459,
   607: 8862441,
   614: 8862461,
   602: 8862438,
   622: 8862455,
   621: 8862453,
   633: 8862465,
   630: 8862464,
   642: 8862467,
   613: 8862447,
   652: 8862469,
   658: 8862470,
   625: 8862458,
   627: 8862460,
   649: 8862473,
   629: 8862463,
   639: 8862474,
   653: 8862477,
   623: 8862456,
   647: 8862479,
   644: 8862478,
   632: 8862466,
   659: 8862482,
   657: 8862483,
   641: 8862476,
   660: 8862485,
   661: 8862486,
   713: 8862487,
   638: 8862472,
   634: 8862468,
   667: 8862490,
   668: 8862492,
   706: 8862493,
   637: 8862471,
   628: 8862462,
   681: 8862494,
   691: 8862495,
   624: 8862457,
   663: 8862496,
   650: 8862484,
   688: 8862500,
   669: 8862501,
   680: 8862502,
   674: 8862503,
   687: 8862504,
   656: 8862491,
   646: 8862481,
   640: 8862475,
   683: 8862509,
   643: 8862510,
   673: 8862508,
   655: 8862489,
   676: 8862512,
   671: 8862506,
   670: 8862505,
   696: 8862516,
   726: 8862517,
   675: 8862511,
   740: 8862519,
   739: 8862520,
   678: 8862514,
   679: 8862515,
   690: 8862523,
   682: 8862518,
   666: 8862499,
   727: 8862525,
   665: 8862498,
   664: 8862497,
   751: 8862527,
   729: 8862528,
   741: 8862530,
   677: 8862513,
   719: 8862533,
   709: 8862535,
   705: 8862537,
   702: 8862534,
   735: 8862539,
   684: 8862521,
   672: 8862507,
   699: 8862531,
   703: 8862536,
   853: 8862544,
   654: 8862488,
   704: 8862538,
   692: 8862526,
   689: 8862524,
   714: 8862545,
   371: 8862224,
   685: 8862522,
   730: 8862550,
   710: 8862542,
   760: 8862553,
   762: 8862554,
   716: 8862546,
   788: 8862556,
   732: 8862557,
   701: 8862532,
   711: 8862543,
   718: 8862548,
   707: 8862540,
   787: 8862561,
   758: 8862562,
   725: 8862552,
   738: 8862565,
   802: 8862566,
   743: 8862567,
   697: 8862529,
   717: 8862547,
   763: 8862569,
   736: 8862563,
   619: 8862451,
   728: 8862555,
   836: 8862573,
   724: 8862551,
   757: 8862575,
   774: 8862577,
   750: 8862576,
   734: 8862560,
   708: 8862541,
   764: 8862581,
   752: 8862578,
   731: 8862558,
   786: 8862583,
   785: 8862584,
   737: 8862564,
   798: 8862586,
   754: 8862579,
   771: 8862587,
   773: 8862588,
   766: 8862589,
   733: 8862559,
   780: 8862592,
   742: 8862568,
   777: 8862594,
   784: 8862595,
   720: 8862549,
   747: 8862574,
   749: 8862598,
   800: 8862599,
   769: 8862590,
   645: 8862480,
   804: 8862602,
   814: 8862603,
   801: 8862604,
   822: 8862605,
   907: 8862606,
   744: 8862570,
   745: 8862571,
   778: 8862597,
   776: 8862609,
   759: 8862582,
   761: 8862585,
   378: 8862234,
   772: 8862593,
   775: 8862596,
   790: 8862608,
   803: 8862616,
   797: 8862615,
   833: 8862618,
   817: 8862619,
   844: 8862620,
   834: 8862621,
   857: 8862622,
   789: 8862607,
   796: 8862614,
   819: 8862625,
   791: 8862610,
   846: 8862628,
   755: 8862580,
   823: 8862630,
   793: 8862612,
   794: 8862613,
   840: 8862633,
   824: 8862634,
   806: 8862623,
   807: 8862624,
   792: 8862611,
   827: 8862636,
   799: 8862617,
   770: 8862591,
   829: 8862638,
   854: 8862641,
   839: 8862642,
   746: 8862572,
   369: 8862220,
   826: 8862635,
   873: 8862644,
   828: 8862637,
   365: 8862214,
   368: 8862218,
   830: 8862639,
   867: 8862647,
   863: 8862648,
   813: 8862627,
   815: 8862629,
   843: 8862646,
   877: 8862652,
   865: 8862653,
   812: 8862626,
   842: 8862655,
   880: 8862657,
   821: 8862632,
   848: 8862650,
   847: 8862649,
   820: 8862631,
   841: 8862645,
   885: 8862662,
   355: 8862663,
   869: 8862665,
   856: 8862656,
   892: 8862667,
   852: 8862651,
   870: 8862669,
   875: 8862670,
   831: 8862640,
   920: 8862672,
   866: 8862666,
   872: 8862673,
   783: 8862601,
   781: 8862600,
   883: 8862675,
   862: 8862661,
   896: 8862677,
   859: 8862659,
   858: 8862658,
   343: 8862177,
   905: 8862680,
   855: 8862654,
   884: 8862682,
   889: 8862683,
   904: 8862684,
   868: 8862668,
   837: 8862643,
   876: 8862676,
   895: 8862688,
   860: 8862660,
   924: 8862690,
   887: 8862686,
   874: 8862674,
   911: 8862693,
   926: 8862694,
   878: 8862678,
   888: 8862687,
   864: 8862664,
   901: 8862697,
   879: 8862679,
   886: 8862685,
   894: 8862692,
   913: 8862701,
   922: 8862702,
   893: 8862691,
   899: 8862698,
   909: 8862704,
   914: 8862706,
   882: 8862681,
   363: 8862210,
   918: 8862708,
   929: 8862709,
   919: 8862711,
   897: 8862695,
   930: 8862713,
   293: 8862109,
   871: 8862671,
   1064: 8862714,
   900: 8862699,
   936: 8862716,
   890: 8862689,
   941: 8862718,
   939: 8862719,
   947: 8862721,
   898: 8862696,
   364: 8862212,
   916: 8862710,
   910: 8862705,
   943: 8862724,
   925: 8862720,
   908: 8862703,
   902: 8862700,
   928: 8862723,
   956: 8862729,
   362: 8862208,
   912: 8862707,
   961: 8862731,
   921: 8862715,
   966: 8862733,
   935: 8862734,
   932: 8862726,
   942: 8862735,
   972: 8862738,
   931: 8862725,
   944: 8862736,
   934: 8862728,
   959: 8862742,
   927: 8862722,
   957: 8862745,
   971: 8862747,
   917: 8862712,
   361: 8862748,
   945: 8862737,
   933: 8862727,
   968: 8862751,
   950: 8862741,
   923: 8862717,
   949: 8862740,
   974: 8862755,
   993: 8862757,
   946: 8862758,
   979: 8862760,
   958: 8862749,
   953: 8862762,
   948: 8862739,
   991: 8862764,
   1002: 8862765,
   955: 8862746,
   951: 8862743,
   964: 8862754,
   962: 8862752,
   960: 8862750,
   937: 8862730,
   965: 8862756,
   359: 8862772,
   1000: 8862773,
   986: 8862774,
   952: 8862744,
   1022: 8862777,
   987: 8862775,
   1023: 8862780,
   996: 8862781,
   970: 8862763,
   969: 8862761,
   973: 8862766,
   990: 8862779,
   981: 8862770,
   980: 8862769,
   978: 8862768,
   1019: 8862788,
   360: 8862205,
   994: 8862783,
   1045: 8862790,
   1012: 8862791,
   988: 8862776,
   989: 8862778,
   940: 8862732,
   997: 8862785,
   963: 8862753,
   1004: 8862792,
   992: 8862782,
   967: 8862759,
   999: 8862787,
   1011: 8862797,
   1003: 8862801,
   1030: 8862803,
   1013: 8862804,
   1015: 8862798,
   1044: 8862806,
   1046: 8862807,
   995: 8862784,
   1005: 8862793,
   1018: 8862802,
   982: 8862771,
   1036: 8862812,
   1033: 8862814,
   1020: 8862805,
   1006: 8862794,
   1056: 8862817,
   1016: 8862799,
   998: 8862786,
   1073: 8862820,
   1028: 8862813,
   1027: 8862811,
   1017: 8862800,
   1001: 8862789,
   1025: 8862809,
   1008: 8862795,
   356: 8862199,
   1010: 8862796,
   1057: 8862827,
   1076: 8862828,
   1072: 8862829,
   1026: 8862810,
   975: 8862767,
   1034: 8862818,
   1040: 8862823,
   1039: 8862822,
   1055: 8862835,
   1042: 8862825,
   1047: 8862830,
   1048: 8862831,
   1058: 8862838,
   1078: 8862839,
   1059: 8862840,
   1075: 8862841,
   1029: 8862842,
   1041: 8862824,
   1024: 8862808,
   1090: 8862846,
   1079: 8862847,
   1049: 8862832,
   1051: 8862834,
   1032: 8862816,
   1031: 8862815,
   1054: 8862837,
   1137: 8862853,
   1097: 8862854,
   1035: 8862819,
   1102: 8862856,
   1103: 8862857,
   1108: 8862858,
   1098: 8862859,
   1077: 8862860,
   1070: 8862851,
   1050: 8862833,
   1068: 8862849,
   1061: 8862844,
   1066: 8862848,
   1043: 8862826,
   1126: 8862866,
   1069: 8862850,
   1060: 8862843,
   1063: 8862845,
   1085: 8862864,
   1080: 8862871,
   1105: 8862872,
   1074: 8862855,
   1141: 8862874,
   1095: 8862870,
   1156: 8862876,
   1081: 8862861,
   1112: 8862878,
   1091: 8862867,
   1084: 8862863,
   1125: 8862881,
   1101: 8862875,
   1106: 8862879,
   1093: 8862869,
   1127: 8862885,
   1071: 8862852,
   1123: 8862887,
   1038: 8862821,
   358: 8862203,
   1087: 8862865,
   1099: 8862873,
   1092: 8862868,
   1082: 8862862,
   1134: 8862894,
   1128: 8862896,
   1122: 8862895,
   1151: 8862898,
   1160: 8862899,
   1131: 8862900,
   1143: 8862901,
   357: 8862201,
   1052: 8862902,
   1053: 8862836,
   1107: 8862880,
   1124: 8862897,
   1147: 8862905,
   1179: 8862906,
   1155: 8862908,
   1152: 8862909,
   1110: 8862883,
   1109: 8862882,
   1118: 8862892,
   1116: 8862890,
   1181: 8862915,
   1117: 8862891,
   1111: 8862884,
   1142: 8862913,
   1138: 8862910,
   1113: 8862886,
   1161: 8862920,
   1133: 8862904,
   1212: 8862921,
   1136: 8862907,
   1165: 8862922,
   1149: 8862923,
   1157: 8862924,
   1194: 8862926,
   1177: 8862927,
   1132: 8862903,
   1104: 8862877,
   1191: 8862930,
   1139: 8862911,
   1148: 8862918,
   1140: 8862912,
   1183: 8862934,
   1158: 8862925,
   353: 8862195,
   1175: 8862938,
   1178: 8862939,
   1192: 8862940,
   1201: 8862941,
   1197: 8862942,
   1205: 8862943,
   1167: 8862944,
   1146: 8862917,
   1174: 8862937,
   ...}}}